### ISSUE TITLE
the petal area makes unnecessary scroll area.

### ISSUE THREAD

**Issue by charmingpark** [jhammann/sakura#19]
even the sample page shows us it makes scroll area, which even unstable.
it need to be fixed.

**Comment by Muska-Ami** [comment]
I add a style to fix it:
```css
.sakura {
    position: relative;
}

**Comment by vaishnav67** [comment]
Changing the css value to
```css
.sakura {
  pointer-events: none;
  position: fixed; }
  ```
can fix it
